### ISSUE TITLE
Balance doesn't show after logout and login

### ISSUE THREAD

**Issue by Bios-Marcel** [isp-insoft-gmbh/MeMate#23]
![image](https://user-images.githubusercontent.com/19377618/140314013-396b1026-fd5a-4c15-b23f-b91ea8195e51.png)

**Comment by Blanco27** [comment]
Fixed #c24b99638df838ed82486b3cbf2315b8690d66b9

**Comment by Blanco27** [comment]
Fixed c24b99638df838ed82486b3cbf2315b8690d66b9
